### PR TITLE
Extracts redirect matching logic to its own match_redirect method.

### PR DESCRIPTION
**Pull request by nicholasio**
### Description of the Change
Introduces a new `match_redirect` method and updates `maybe_redirect` to use this new method.

It also introduces a `srm_match_redirect` function to expose matching redirect logic to themes and plugins.

### Alternate Designs
See https://github.com/10up/safe-redirect-manager/issues/197

### Benefits
Code is more testable now and maybe_redirect now only does one thing.

### Possible Drawbacks
None

### Verification Process
Manual testing

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jeffpaul** [comment]
@nicholasio thanks for the PR, it's greatly appreciated!  I've pinged @tlovett1 for review on this in planning for getting it into our next milestoned release, so stay tuned for any feedback from that review.

**Review by dinhtungdu — DISMISSED** [review]
LGTM 👍

Edit: This is just my preference, but if we return early in `maybe_redirect` method, we can save one level of indentation:
```
if ( empty(  $matched_redirect ) ) {
    return;
}

// Do the rest
...
```

**Comment by nicholasio** [comment]
@dinhtungdu done, that is generally my preference as well.

**Review by dinhtungdu — APPROVED** [review]
🎉

**Pull request merged**
