### PR TITLE
Export redirects to csv

### PR DESCRIPTION
**Pull request by zamanq**
### Description of the Change
Added a new WP CLI command to export the redirects into a csv file.

### How to test the Change
To test the feature, please run `wp safe-redirect-manager export_csv` This will create a csv file with the default name srm-redirects.csv. If you want to add a different name for the csv file then you can do something like `wp safe-redirect-manager export_csv --filename=sample-redirects`

*Please note that it is not necessary to provide the .csv extension for the name, it'll be appended automatically.

### Changelog Entry

> Added - WP-CLI command `export` to exporting redirects into a CSV file.

### Credits
Props @zamanq @jeffpaul 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by jeffpaul** [comment]
@zamanq are you still working on this or have you abandoned effort here such that this should be closed?

**Comment by zamanq** [comment]
Hi @jeffpaul, Yeah I planned to work on it but then got busy with client work and eventually forgot about it, sorry. I think I'll re-visit the implementation idea in a near future. You can close this PR btw.

Thank you!

**Review by Sidsector9 — APPROVED** [review]
Thank you for working on this, tested and works well 👍

**Review by Sidsector9 — APPROVED** [review]
Thank you for working on this, testing and works well 👍

**Review by Sidsector9 — APPROVED** [review]
Thank you for working on this, testing and works well 👍

**Pull request merged**
