### PR TITLE
Add user capability checking later

### LINKED ISSUE #177: Notice: map_meta_cap was called <strong> incorrectly </strong>. The post type jp_sitemap has not been registered, so checking the ability to "edit_post" against such a post may not be reliable.
**Describe the bug**
When using Jetpack 7.6 and SRM, you see this notice when cron runs:

```
Notice: map_meta_cap was called <strong> incorrectly </strong>. The post type jp_sitemap has not been registered, so checking the ability to "edit_post" against such a post may not be reliable. Read as <a href="https://codex.wordpress.org/en-US:Debugging_a_WordPress Network"> Debugging WordPress </a> for more information. (This message was added in version 4.4.0.) In in /chroot/var/www/wp-includes/functions.php on line 4773
```

Stack trace:

```
[/chrootwp-includes/functions.php:4773 trigger_error(), /chrootwp-includes/capabilities.php:155 _doing_it_wrong(), /chrootwp-includes/class-wp-user.php:740 map_meta_cap(), /chrootwp-includes/capabilities.php:649 WP_User->has_cap(), /chrootwp-content/plugins/safe-redirect-manager/safe-redirect-manager.php:505 current_user_can(), /chrootwp-includes/class-wp-hook.php:288 SRM_Safe_Redirect_Manager->action_save_post(), /chrootwp-includes/class-wp-hook.php:310 WP_Hook->apply_filters(), /chrootwp-includes/plugin.php:465 WP_Hook->do_action(), /chrootwp-includes/post.php:3951 do_action('save_post'), /chrootwp-includes/post.php:4028 wp_insert_post(), /chrootwp-includes/post.php:2988 wp_update_post(), /chrootwp-content/mu-plugins/jetpack/modules/sitemaps/sitemap-librarian.php:210 wp_trash_post(), /chrootwp-content/mu-plugins/jetpack/modules/sitemaps/sitemap-librarian.php:184 Jetpack_Sitemap_Librarian->delete_sitemap_type_data(), /chrootwp-content/mu-plugins/jetpack/modules/sitemaps/sitemaps.php:507 Jetpack_Sitemap_Librarian->delete_all_stored_sitemap_data(), /chrootwp-includes/class-wp-hook.php:286 Jetpack_Sitemap_Manager->callback_action_purge_data(), /chrootwp-includes/class-wp-hook.php:310 WP_Hook->apply_filters(), /chrootwp-includes/plugin.php:465 WP_Hook->do_action(), /chrootwp-content/mu-plugins/jetpack/class.jetpack.php:452 do_action('jetpack_sitemaps_purge_data'), /chrootwp-includes/class-wp-hook.php:286 Jetpack::upgrade_on_load(), /chrootwp-includes/class-wp-hook.php:310 WP_Hook->apply_filters(), /chrootwp-includes/plugin.php:465 WP_Hook->do_action(), /chrootwp-settings.php:546 do_action('wp_loaded')
```

When `jp_sitemap` posts get deleted during the sitemap cron, SRM runs a capability check on every post during the `save_post` event, triggering a “doing it wrong” warning.

### PR DESCRIPTION
**Pull request by rebeccahum**
### Description of the Change

We should add the `current_user_can` cap checking later to prevent the notice being thrown in #177 during JP sitemap cron event runs.  Fixes #177.  

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by adamsilverstein** [comment]
This looks good @rebeccahum - looks like some tests are failing though. Once we get that fixed this can be merged.

**Comment by rebeccahum** [comment]
@adamsilverstein Hiya, can you check the config?  This is the reason why I'm seeing that the tests are failing:

```
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to MySQL server on 'localhost' (111)'
```

**Comment by adamsilverstein** [comment]
Strange, the config works in develop. digging.

**Comment by adamsilverstein** [comment]
Looks like some changes in develop fix this, I merged the current version into your branch...

**Review by adamsilverstein — APPROVED** [review]
Nice work. Thanks for your contribution @rebeccahum!

**Comment by rebeccahum** [comment]
@jeffpaul Do you know when this will be merged to master?

**Comment by jeffpaul** [comment]
@rebeccahum thanks for the ping!  We're working on a couple other plugin releases, many in line with updates for WordPress 5.3, but have started to prep a v1.9.3 release for Safe Redirect Manager mainly around this issue.  I'll keep you posted as this gets a determined release date, thanks!

**Comment by jeffpaul** [comment]
@rebeccahum note that v1.9.3 was released on Wednesday, so it should now be available for your needs.  Thanks again for sharing your report, PR, and keeping in touch during the release process!

**Pull request merged**
