### PR TITLE
Indicate WP 6.0 support.

### LINKED ISSUE #267: Test against WordPress 6.0
Is your enhancement related to a problem? Please describe.
Once WordPress 6.0 is released, we'll want to test Safe Redirect Manager to see if any incompatibility issues arise.

Describe the solution you'd like

- [x] test Safe Redirect Manager on WordPress 6.0
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [x] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

Designs
n/a

Describe alternatives you've considered
none

Additional context
Related: #258, #245, #232, #227, #204

### PR DESCRIPTION
**Pull request by peterwilsoncc**
### Description of the Change

Indicate WP 6.0 support in the wordpress.org readme file.

This pull request targets `develop`, a follow up PR will be created to fix the issue and merge to `trunk`.

See #267

### Verification Process

- Tested on single and multi site install
- Created fixed redirect
- Created wildcard redirect
- Created regex redirect (various forms of regex)

Each redirect was tested by saving with multiple slash set ups
- no leading, no trailing
- leading, no trailing
- no leading, trailing
- no leading, no trailing
(In some configs, this was normalised upon save)

Each of these worked in 6.0 as they did in earlier WP releases.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests passed.

### Changelog Entry

N/A

### Credits

Props @peterwilsoncc

### CODE REVIEW

**Comment by jeffpaul** [comment]
@peterwilsoncc curious on the PHP 5.6 minimum, was that set to match the base WP expectation or is there space for us to bump that (likely in a separate PR) to make maintaining things here easier?

**Review by jeffpaul — APPROVED** [review]

**Review by iamdharmesh — APPROVED** [review]

**Comment by iamdharmesh** [comment]
@peterwilsoncc  Thanks for verifying with multiple slash setups as well. I think we should add it in e2e tests as well. I will add it in cypress once get some OSS time. 
```
no leading, no trailing
leading, no trailing
no leading, trailing
no leading, no trailing
```

**Comment by peterwilsoncc** [comment]
@jeffpaul I took it from the setting in the php compatibility check https://github.com/10up/safe-redirect-manager/blob/ec4487637cd80ce900d15cad12ceded451dd4a5c/.github/workflows/php-compatibility.yml#L32

It's possibly worth bumping in another ticket, even without updating code, so the plugin can use modern coding practices.

**Comment by jeffpaul** [comment]
@iamdharmesh note that I moved those e2e tests into a new issue: #271.

**Pull request merged**
