### PR TITLE
Finnish translations & load_plugin_textdomain hotfix

### PR DESCRIPTION
**Pull request by Liblastic**
- Finnish translations
- Fixes load_plugin_textdomain()

### CODE REVIEW

**Comment by jeffpaul** [comment]
@Liblastic thanks for the PR!

@adamsilverstein don't all translations now happen on translate.wordpress.org?  if so, maybe cherry-pick the safe-redirect-manager.php commit as needed from this PR for the v2.0 release?

**Review by dinhtungdu — COMMENTED** [review]
The Finnish translation works but all translation should be done on translate.wordpress.org. We should pick the change in `safe-redirect-manager.php` only. For the existing translated strings in this PR, we can import them into Finnish project of Safe Redirect Manager on Polyglot: https://translate.wordpress.org/locale/fi/default/wp-plugins/safe-redirect-manager/

**Comment by jeffpaul** [comment]
@Liblastic would you mind submitting the Finnish translations on the official [Translating WordPress site](https://translate.wordpress.org/locale/fi/default/wp-plugins/safe-redirect-manager/)?

**Comment by jeffpaul** [comment]
Handled the base plugin file change in e5fcb0ede6eb9d2628c40d56e78108d68b78c5f0.

**Comment by jeffpaul** [comment]
Remaining sk_SK translations exist or have been submitted to [translate.wordpress.org](https://translate.wordpress.org/projects/wp-plugins/safe-redirect-manager/dev/sk/default/).  Thus this PR has been folded into separate places (1.10.0 release PR and translate.wordpress.org), so closing this PR.

**Pull request closed without merging**
