### PR TITLE
Custom protocol per route

### LINKED ISSUE #46: Redirection to HTTPS
It would be super useful to me if this plugin could handle redirecting http to https for certain URL's. Thoughts on this @danielbachhuber ?

### PR DESCRIPTION
**Pull request by jayedul**
### Description of the Change
Custom protocol selection feature per route implemented. 

Closes #46 

### How to test the Change
- Add/edit a redirect rule
- Choose `http` or `https` in Redirect Protocol section
- Visit the route
- Check if it redirects to the protocol you've selected. 

### Changelog Entry

> Added - Custom redirect protocol per route

### Credits

Props @jayedul 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by Sidsector9 — CHANGES_REQUESTED** [review]
@jayedul correct me if I'm wrong, the issue requests to implement a checkbox which enforces SSL rather than providing an option to choose the protocol.

**Comment by jayedul** [comment]
@Sidsector9 Not to force, by default it will use current protocol. However if users want, they can change the protocol to either http/s for individual routes.

https://github.com/10up/safe-redirect-manager/issues/46#issue-21901904

**Comment by jeffpaul** [comment]
@Sidsector9 bumping back to you for review

**Comment by Sidsector9** [comment]
@jayedul after discussing this internally, we arrived at the conclusion that it would be better to only enforce https and remove the option to switch to http.

More details here - https://10up.slack.com/archives/C84M9AA06/p1684232341604279

**Comment by jayedul** [comment]
@Sidsector9 Now radio button removed, and single checkbox added to enable force HTTPS redirect.
Screenshot 2023-06-01 at 2 45 30 PM

**Comment by jeffpaul** [comment]
@Sidsector9 back to you for review here

**Review by Sidsector9 — APPROVED** [review]
Apologies for the delay in review. Thanks for the changes! LGTM 👍

**Pull request merged**
