### PR TITLE
Deprecated error in importing fix

### LINKED ISSUE #283: auto_detect_line_endings is deprecated as of PHP 8.1
### Is your enhancement related to a problem? Please describe.

When validating one of our sites, this was found via PHPCS:

_INI directive 'auto_detect_line_endings' is deprecated since PHP 8.1_

This applies to /inc/functions.php line 336:

`@ini_set( 'auto_detect_line_endings', true );`

### Designs

_No response_

### Describe alternatives you've considered

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jayedul**
### Description of the Change
`@ini_set( 'auto_detect_line_endings', true );` removed from csv import script since latest PHP versions manages line endings automatically. 

Closes #283 

### How to test the Change

- Create a CSV file for SRM importer
- Import from different OS
- It should work as usual

### Changelog Entry

> Fixed - Deprecated notice

### Credits

Props @dhewer @jayedul 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by Sidsector9 — COMMENTED** [review]
@jayedul this plugin has a minimum PHP support for 7.4. The `auto_detect_line_endings` directive was deprecated in 8.1 and will be removed in 9.0.

Do you think we should remove this entirely, or conditionally set it to true for PHP versions < 8.1?

**Review by Sidsector9 — COMMENTED** [review]
@jayedul this plugin has a minimum PHP support for 7.4. The `auto_detect_line_endings` directive was deprecated in 8.1 and will be removed in 9.0.

Do you think instead of removing this entirely, we should maybe conditionally set it for PHP versions < 8.1?

**Comment by ravinderk** [comment]
@jayedul, did you get a chance to check @Sidsector9 [review](https://github.com/10up/safe-redirect-manager/pull/327#pullrequestreview-1523879222)?

**Review by Sidsector9 — APPROVED** [review]
Thanks for the changes! LGTM 🎉

**Pull request merged**
